# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prep_all_sample_func_vec <- function(abun_tab, func_tab) {
    .Call('_FuncDiv_prep_all_sample_func_vec', PACKAGE = 'FuncDiv', abun_tab, func_tab)
}

prep_all_sample_func_taxa_vec <- function(abun_tab, func_tab) {
    .Call('_FuncDiv_prep_all_sample_func_taxa_vec', PACKAGE = 'FuncDiv', abun_tab, func_tab)
}

prep_func_contributor_dimnames <- function(abun_tab, func_tab) {
    .Call('_FuncDiv_prep_func_contributor_dimnames', PACKAGE = 'FuncDiv', abun_tab, func_tab)
}

rbiom_par_unifrac <- function(sparseMatrix, tree, weighted) {
    .Call('_FuncDiv_rbiom_par_unifrac', PACKAGE = 'FuncDiv', sparseMatrix, tree, weighted)
}

